CATALOG = [
    {"key": "pnl", "title_tj": "P&L (Foyda/Zarar)",
     "desc_tj": "Tushum, COGS, yalpi va sof foyda", "note_tj": None,
     "formats": ["pdf", "excel", "csv"]},
    {"key": "sales", "title_tj": "Sotuvlar",
     "desc_tj": "Kunlik sotuv va top mahsulot", "note_tj": None,
     "formats": ["pdf", "excel", "csv"]},
    {"key": "inventory", "title_tj": "Ombor zaxirasi",
     "desc_tj": "Mahsulot boyicha zaxira qiymati",
     "note_tj": "Joriy zaxira snapshot", "formats": ["pdf", "excel", "csv"]},
    {"key": "dead_stock", "title_tj": "Qotib qolgan zaxira",
     "desc_tj": "DEAD / SLOW / AT-RISK",
     "note_tj": "Joriy zaxira snapshot", "formats": ["pdf", "excel", "csv"]},
    {"key": "supplier", "title_tj": "Supplier anomaliyalari",
     "desc_tj": "Narx oshib ketgan supplierlar",
     "note_tj": "Aniqlash oynasi: oxirgi 180 kun",
     "formats": ["pdf", "excel", "csv"]},
    {"key": "variance", "title_tj": "Inventarizatsiya farqi",
     "desc_tj": "Fizik sanoq vs tizim",
     "note_tj": "Report davri ishlatiladi",
     "formats": ["pdf", "excel", "csv"]},
    {"key": "forecast", "title_tj": "Prognoz",
     "desc_tj": "Tushum + stockout + excess",
     "note_tj": "Prognoz oynasi: oxirgi 90 kun",
     "formats": ["pdf", "excel", "csv"]},
    {"key": "billing", "title_tj": "Obuna va tolovlar",
     "desc_tj": "Invoicelar va subscription",
     "note_tj": "Report davri ishlatiladi",
     "formats": ["pdf", "excel", "csv"]},
]
